 # RL algorithm options
initial_collect_steps: 100
collect_steps_per_iteration: 1 
replay_buffer_max_length: 10000
batch_size: 42 
learning_rate: 0.0001

# Logging and evaluation options
log_interval: 1000
num_eval_episodes: 1000
eval_interval: Null

# QNet options
fc_layer_params: # the number of neurons in each dense layer
  - 32
  - 16
  - 8
start_epsilon: 0.3 
end_epsilon: 0. 
qnet_target_update_tau: 0.09
qnet_target_update_period: 1
discount_factor: 0.95