 # RL algorithm options
initial_collect_steps: 100
collect_steps_per_iteration: 1 
replay_buffer_max_length: 10000
batch_size: 64
learning_rate: 0.0001

# Logging and evaluation options
log_interval: 1000
num_eval_episodes: 2000
eval_interval: 2000

# QNet options
fc_layer_params: # the number of neurons in each dense layer
  - 128
  - 64
start_epsilon: 0.6
end_epsilon: 0.01
qnet_target_update_tau: 0.005
qnet_target_update_period: 1000
discount_factor: 0.95

# Training run options
epochs: 3

# Training data
training_data:
  - "data/GBPEUR=X_08_08_23.csv"
  - "data/GBPUSD=X_08_08_23.csv"
  - "data/GBPJPY=X_08_08_23.csv"